### ISSUE TITLE
Cannot show PHP menu in current GNOME Desktop

### ISSUE THREAD

**Issue by pradzikowski** [addiks/gedit-phpide#4]
Hi i have problem with your plugin. Im just installed it like it was written in your instruction, i was create catalog with local git repo and one `index.php` file. 

 When  i open file in gedit i have this message in terminal, and i thing it is problem with current version of gedit. 
![zrzut ekranu z 2017-06-15 14-38-23](https://user-images.githubusercontent.com/1573220/27181591-78bae0ec-51d8-11e7-88a6-2df53fe5e1c2.png)

My gedit version : ```gedit - Version 3.22.0```
My Python3 version: ```Python 3.5.3```

**Comment by addiks** [comment]
What distribution and version of it are you using? The fastest way for me to reproduce the problem is to install it in a VM and see what happens when using the plugin there. From the error-message it looks like your gedit does not have a main menu that the plugin could attach it's sub-menu ("PHP") to. Or the way to access it has changed somewhere between 3.18 (which i currently use) and 3.22.

**Comment by pradzikowski** [comment]
Oh, yes i forgot about OS. I use ubuntu 17.04.

**Comment by addiks** [comment]
I have installed ubuntu-17.04 with gedit-3.22 in a VM and it did run fine with the plugin. At the moment i cannot reproduce the problem so i need more information. What other gedit-plugins do you have installed? Do any of these tamper with the main menu? Are you using unity or another desktop-manager? What PPA's (package-repositories) are you using?

**Comment by pradzikowski** [comment]
i have only installed `gedit-plugins`, and i currently disable all plugins except phpide. Im working now on ubungu with gnome maybe here is the problem ?

**Comment by addiks** [comment]
I can now reproduce the error-message in gnome. Seems like gnome has indeed get rid of the old application-menu (there seems to be a different menu, but the one i know seems gone.) The rest of the plugin seems to work, at least auto-complete works here. I will look into what needs to be done to get the PHP menu show up in this new menu or look for a different solution if that is not possible. I cannot say how long this will take me because i don't know all the details yet (and how much time i can actually put into this), but i will try. Thanks for reporting this.

**Comment by addiks** [comment]
Can you please try the current version i have just pushed to this repository? The PHP Menu should now pop up in the application-menu in the top-bar. I would have added the PHP-menu to the menu in the gedit window itself (or in the tools submenu), but i found no way (as of now) to get that to work.

**Comment by pradzikowski** [comment]
It works ! Thx :) 
![image](https://user-images.githubusercontent.com/1573220/27255835-bdef7568-53a6-11e7-98a4-d62cfc70c3e2.png)
